#define MAX_TRACE_PATHBUF_LEN 256

#define trace_android_fs_data_start_template(x, ...) {}
#define trace_android_fs_data_end_template(x, ...) {}
#define trace_android_fs_fsync_end(x, ...) {}
#define trace_android_fs_fsync_start(x, ...) {}
#define trace_android_fs_fsync_start_enabled(x, ...) 0
#define trace_android_fs_fsync_start_template(x, ...) {}
#define trace_android_fstrace_get_pathname(x, ...) {}
#define android_fstrace_get_pathname(x, ...) "/dev/null"

#define trace_ext4__bitmap_load(x, ...) {}
#define trace_ext4__es_extent(x, ...) {}
#define trace_ext4__es_shrink_enter(x, ...) {}
#define trace_ext4__fallocate_mode(x, ...) {}
#define trace_ext4__map_blocks_enter(x, ...) {}
#define trace_ext4__map_blocks_exit(x, ...) {}
#define trace_ext4__mb_new_pa(x, ...) {}
#define trace_ext4__mballoc(x, ...) {}
#define trace_ext4__page_op(x, ...) {}
#define trace_ext4__trim(x, ...) {}
#define trace_ext4__truncate(x, ...) {}
#define trace_ext4__write_begin(x, ...) {}
#define trace_ext4__write_end(x, ...) {}
#define trace_ext4_alloc_da_blocks(x, ...) {}
#define trace_ext4_allocate_blocks(x, ...) {}
#define trace_ext4_allocate_inode(x, ...) {}
#define trace_ext4_begin_ordered_truncate(x, ...) {}
#define trace_ext4_collapse_range(x, ...) {}
#define trace_ext4_da_release_space(x, ...) {}
#define trace_ext4_da_reserve_space(x, ...) {}
#define trace_ext4_da_update_reserve_space(x, ...) {}
#define trace_ext4_da_write_begin(x, ...) {}
#define trace_ext4_da_write_end(x, ...) {}
#define trace_ext4_da_write_pages(x, ...) {}
#define trace_ext4_da_write_pages_extent(x, ...) {}
#define trace_ext4_direct_IO_enter(x, ...) {}
#define trace_ext4_direct_IO_exit(x, ...) {}
#define trace_ext4_discard_blocks(x, ...) {}
#define trace_ext4_discard_preallocations(x, ...) {}
#define trace_ext4_drop_inode(x, ...) {}
#define trace_ext4_es_cache_extent(x, ...) {}
#define trace_ext4_es_find_delayed_extent_range_enter(x, ...) {}
#define trace_ext4_es_find_delayed_extent_range_exit(x, ...) {}
#define trace_ext4_es_insert_extent(x, ...) {}
#define trace_ext4_es_lookup_extent_enter(x, ...) {}
#define trace_ext4_es_lookup_extent_exit(x, ...) {}
#define trace_ext4_es_remove_extent(x, ...) {}
#define trace_ext4_es_shrink(x, ...) {}
#define trace_ext4_es_shrink_count(x, ...) {}
#define trace_ext4_es_shrink_scan_enter(x, ...) {}
#define trace_ext4_es_shrink_scan_exit(x, ...) {}
#define trace_ext4_evict_inode(x, ...) {}
#define trace_ext4_ext_convert_to_initialized_enter(x, ...) {}
#define trace_ext4_ext_convert_to_initialized_fastpath(x, ...) {}
#define trace_ext4_ext_handle_unwritten_extents(x, ...) {}
#define trace_ext4_ext_in_cache(x, ...) {}
#define trace_ext4_ext_load_extent(x, ...) {}
#define trace_ext4_ext_map_blocks_enter(x, ...) {}
#define trace_ext4_ext_map_blocks_exit(x, ...) {}
#define trace_ext4_ext_put_in_cache(x, ...) {}
#define trace_ext4_ext_remove_space(x, ...) {}
#define trace_ext4_ext_remove_space_done(x, ...) {}
#define trace_ext4_ext_rm_idx(x, ...) {}
#define trace_ext4_ext_rm_leaf(x, ...) {}
#define trace_ext4_ext_show_extent(x, ...) {}
#define trace_ext4_fallocate_enter(x, ...) {}
#define trace_ext4_fallocate_exit(x, ...) {}
#define trace_ext4_find_delalloc_range(x, ...) {}
#define trace_ext4_forget(x, ...) {}
#define trace_ext4_free_blocks(x, ...) {}
#define trace_ext4_free_inode(x, ...) {}
#define trace_ext4_fsmap_class(x, ...) {}
#define trace_ext4_fsmap_low_key(x, ...) {}
#define trace_ext4_fsmap_high_key(x, ...) {}
#define trace_ext4_fsmap_mapping(x, ...) {}
#define trace_ext4_get_implied_cluster_alloc_exit(x, ...) {}
#define trace_ext4_get_reserved_cluster_alloc(x, ...) {}
#define trace_ext4_getfsmap_class(x, ...) {}
#define trace_ext4_getfsmap_low_key(x, ...) {}
#define trace_ext4_getfsmap_high_key(x, ...) {}
#define trace_ext4_getfsmap_mapping(x, ...) {}
#define trace_ext4_ind_map_blocks_enter(x, ...) {}
#define trace_ext4_ind_map_blocks_exit(x, ...) {}
#define trace_ext4_insert_range(x, ...) {}
#define trace_ext4_invalidatepage(x, ...) {}
#define trace_ext4_invalidatepage_op(x, ...) {}
#define trace_ext4_journal_start(x, ...) {}
#define trace_ext4_journal_start_reserved(x, ...) {}
#define trace_ext4_journalled_invalidatepage(x, ...) {}
#define trace_ext4_journalled_write_end(x, ...) {}
#define trace_ext4_load_inode(x, ...) {}
#define trace_ext4_load_inode_bitmap(x, ...) {}
#define trace_ext4_mark_inode_dirty(x, ...) {}
#define trace_ext4_mb_bitmap_load(x, ...) {}
#define trace_ext4_mb_buddy_bitmap_load(x, ...) {}
#define trace_ext4_mb_discard_preallocations(x, ...) {}
#define trace_ext4_mb_new_group_pa(x, ...) {}
#define trace_ext4_mb_new_inode_pa(x, ...) {}
#define trace_ext4_mb_release_group_pa(x, ...) {}
#define trace_ext4_mb_release_inode_pa(x, ...) {}
#define trace_ext4_mballoc_alloc(x, ...) {}
#define trace_ext4_mballoc_discard(x, ...) {}
#define trace_ext4_mballoc_free(x, ...) {}
#define trace_ext4_mballoc_prealloc(x, ...) {}
#define trace_ext4_nfs_commit_metadata(x, ...) {}
#define trace_ext4_other_inode_update_time(x, ...) {}
#define trace_ext4_punch_hole(x, ...) {}
#define trace_ext4_read_block_bitmap_load(x, ...) {}
#define trace_ext4_readpage(x, ...) {}
#define trace_ext4_releasepage(x, ...) {}
#define trace_ext4_remove_blocks(x, ...) {}
#define trace_ext4_request_blocks(x, ...) {}
#define trace_ext4_request_inode(x, ...) {}
#define trace_ext4_sync_file_enter(x, ...) {}
#define trace_ext4_sync_file_exit(x, ...) {}
#define trace_ext4_sync_fs(x, ...) {}
#define trace_ext4_trim_all_free(x, ...) {}
#define trace_ext4_trim_extent(x, ...) {}
#define trace_ext4_truncate_enter(x, ...) {}
#define trace_ext4_truncate_exit(x, ...) {}
#define trace_ext4_unlink_enter(x, ...) {}
#define trace_ext4_unlink_exit(x, ...) {}
#define trace_ext4_write_begin(x, ...) {}
#define trace_ext4_write_end(x, ...) {}
#define trace_ext4_writepage(x, ...) {}
#define trace_ext4_writepages(x, ...) {}
#define trace_ext4_writepages_result(x, ...) {}
#define trace_ext4_zero_range(x, ...) {}
